// Knot & Co — wedding marketplace catalog data.
// Cultural styles, service categories, and a seed of demo vendors.

export const cultures = [
  {
    slug: "south-asian",
    name: "South Asian",
    blurb:
      "Indian, Pakistani, Bangladeshi & Sri Lankan ceremonies — Hindu, Sikh, Jain, Muslim & Christian traditions.",
    accent: "from-rose-400 via-rose-300 to-gold-400",
    hero: "Mehndi nights, sangeet dance floors, baraats and sindoor.",
  },
  {
    slug: "east-asian",
    name: "East Asian",
    blurb:
      "Chinese, Korean, Japanese & Vietnamese weddings — tea ceremonies, hanbok, qipao and modern fusion receptions.",
    accent: "from-rose-200 via-cream to-gold-400",
    hero: "Tea ceremonies, double-happiness banquets and modern fusion receptions.",
  },
  {
    slug: "traditional-canadian",
    name: "Traditional Canadian",
    blurb:
      "Classic Canadian and Western weddings — chapels, vineyards, lakeside lodges and barn venues from coast to coast.",
    accent: "from-cream via-sand to-rose-100",
    hero: "Vineyards, lakeside lodges, white aisles and first dances.",
  },
  {
    slug: "filipino",
    name: "Filipino",
    blurb: "Catholic ceremonies, cord & veil, money dance and barong tagalog elegance.",
    accent: "from-rose-100 via-gold-400 to-rose-300",
    hero: "Cord, veil, coin and the money dance.",
  },
  {
    slug: "middle-eastern-persian",
    name: "Middle Eastern & Persian",
    blurb:
      "Arab, Lebanese, Egyptian, Persian and Turkish weddings — zaffa, sofreh aghd, dabke and hennas.",
    accent: "from-gold-400 via-rose-300 to-rose-500",
    hero: "Zaffa processions, sofreh aghd and late-night dabke.",
  },
  {
    slug: "jewish",
    name: "Jewish",
    blurb:
      "Reform, Conservative & Orthodox ceremonies — chuppah, ketubah, bedeken, hora and seven blessings.",
    accent: "from-cream via-rose-100 to-gold-400",
    hero: "Chuppah, ketubah signing, glass-breaking and the hora.",
  },
  {
    slug: "african-caribbean",
    name: "African & Caribbean",
    blurb:
      "Nigerian, Ghanaian, Ethiopian, Jamaican & Trinidadian weddings — aso ebi, gele tying, jollof tables and soca floors.",
    accent: "from-rose-500 via-gold-400 to-gold-500",
    hero: "Aso ebi, gele tying, jollof and soca til sunrise.",
  },
  {
    slug: "latin-american",
    name: "Latin American",
    blurb:
      "Mexican, Colombian, Peruvian, Argentinian and Brazilian weddings — lazo, arras, mariachi and an hora loca.",
    accent: "from-rose-300 via-rose-400 to-gold-500",
    hero: "Lazo & arras, mariachi serenade and the hora loca.",
  },
  {
    slug: "indigenous-canadian",
    name: "Indigenous Canadian",
    blurb:
      "First Nations, Métis & Inuit ceremonies — smudging, blanket ceremonies and sacred fire traditions, led by Elders.",
    accent: "from-sand via-rose-100 to-rose-300",
    hero: "Smudging, blanket ceremonies and Elder-led traditions.",
  },
  {
    slug: "lgbtq-friendly",
    name: "LGBTQ+ Affirming",
    blurb:
      "Vendors who proudly serve queer couples — affirming officiants, stylists, photographers and venues.",
    accent: "from-rose-200 via-rose-300 to-gold-400",
    hero: "Love is love — vetted vendors who celebrate every couple.",
  },
  {
    slug: "fusion-multicultural",
    name: "Fusion & Multicultural",
    blurb:
      "Two-day, three-event, blended-family weddings — vendors who bridge cultures, languages and menus seamlessly.",
    accent: "from-rose-400 via-rose-200 to-gold-400",
    hero: "When two families, two languages and two menus become one.",
  },
];

// Master service taxonomy — 'all the potential vendors'.
export const serviceCategories = [
  {
    group: "Planning & Coordination",
    items: [
      { slug: "wedding-planner", name: "Wedding Planner", icon: "📋" },
      { slug: "day-of-coordinator", name: "Day-of Coordinator", icon: "📌" },
      { slug: "destination-planner", name: "Destination Planner", icon: "🌴" },
      { slug: "elopement-planner", name: "Elopement Planner", icon: "🏞️" },
    ],
  },
  {
    group: "Venues",
    items: [
      { slug: "banquet-hall", name: "Banquet Hall", icon: "🏛️" },
      { slug: "hotel-ballroom", name: "Hotel Ballroom", icon: "🏨" },
      { slug: "estate-mansion", name: "Estate / Mansion", icon: "🏰" },
      { slug: "vineyard-winery", name: "Vineyard / Winery", icon: "🍇" },
      { slug: "barn-rustic", name: "Barn / Rustic", icon: "🌾" },
      { slug: "garden-outdoor", name: "Garden / Outdoor", icon: "🌳" },
      { slug: "lakefront-beach", name: "Lakefront / Beach", icon: "🌊" },
      { slug: "rooftop-loft", name: "Rooftop / Loft", icon: "🏙️" },
      { slug: "gurudwara", name: "Gurudwara", icon: "🛕" },
      { slug: "mandir-temple", name: "Mandir / Temple", icon: "🕉️" },
      { slug: "mosque", name: "Mosque", icon: "🕌" },
      { slug: "church-chapel", name: "Church / Chapel", icon: "⛪" },
      { slug: "synagogue", name: "Synagogue", icon: "✡️" },
      { slug: "golf-club", name: "Golf Club", icon: "⛳" },
      { slug: "museum-gallery", name: "Museum / Gallery", icon: "🖼️" },
    ],
  },
  {
    group: "Officiants & Religious",
    items: [
      { slug: "civil-officiant", name: "Civil Officiant", icon: "📜" },
      { slug: "pandit-priest", name: "Pandit / Hindu Priest", icon: "🪔" },
      { slug: "granthi", name: "Granthi (Sikh)", icon: "📖" },
      { slug: "imam-nikkah", name: "Imam / Nikkah Officiant", icon: "🕋" },
      { slug: "rabbi", name: "Rabbi", icon: "📿" },
      { slug: "christian-minister", name: "Christian Minister / Priest", icon: "✝️" },
      { slug: "buddhist-monk", name: "Buddhist Monk", icon: "🙏" },
      { slug: "indigenous-elder", name: "Indigenous Elder", icon: "🪶" },
      { slug: "interfaith-officiant", name: "Interfaith Officiant", icon: "🕊️" },
    ],
  },
  {
    group: "Photo & Video",
    items: [
      { slug: "photographer", name: "Photographer", icon: "📷" },
      { slug: "videographer", name: "Videographer", icon: "🎥" },
      { slug: "drone-operator", name: "Drone Operator", icon: "🚁" },
      { slug: "photo-booth", name: "Photo Booth / 360 Booth", icon: "🤳" },
      { slug: "live-stream", name: "Live-Stream Service", icon: "📡" },
      { slug: "live-painter", name: "Live Wedding Painter", icon: "🎨" },
      { slug: "calligrapher", name: "Calligrapher", icon: "🖋️" },
    ],
  },
  {
    group: "Food & Drink",
    items: [
      { slug: "caterer-south-asian", name: "South Asian Caterer", icon: "🍛" },
      { slug: "caterer-east-asian", name: "East Asian Caterer", icon: "🥢" },
      { slug: "caterer-halal", name: "Halal Caterer", icon: "☪️" },
      { slug: "caterer-kosher", name: "Kosher Caterer", icon: "🕎" },
      { slug: "caterer-western", name: "Western / Canadian Caterer", icon: "🍽️" },
      { slug: "caterer-vegan", name: "Vegan / Plant-Based Caterer", icon: "🌱" },
      { slug: "food-truck", name: "Late-Night Food Truck", icon: "🚚" },
      { slug: "bartending", name: "Mobile Bartending", icon: "🍸" },
      { slug: "sommelier", name: "Sommelier / Wine Service", icon: "🍷" },
      { slug: "barista-tea", name: "Barista / Chai / Boba Bar", icon: "☕" },
      { slug: "cake-designer", name: "Wedding Cake Designer", icon: "🎂" },
      { slug: "mithai-sweets", name: "Mithai & Sweet Table", icon: "🍬" },
      { slug: "dessert-grazing", name: "Dessert / Grazing Table", icon: "🍰" },
    ],
  },
  {
    group: "Decor & Florals",
    items: [
      { slug: "florist", name: "Florist", icon: "💐" },
      { slug: "mandap-decor", name: "Mandap & Stage Decor", icon: "🛕" },
      { slug: "chuppah-decor", name: "Chuppah Decor", icon: "🌿" },
      { slug: "ceremony-arch", name: "Ceremony Arch / Backdrop", icon: "🌸" },
      { slug: "lighting-design", name: "Lighting & Uplighting", icon: "💡" },
      { slug: "drape-tent", name: "Drape & Tent Rentals", icon: "⛺" },
      { slug: "furniture-rental", name: "Furniture & Linen Rentals", icon: "🪑" },
      { slug: "tableware-rental", name: "Tableware & China Rentals", icon: "🍽️" },
      { slug: "specialty-signage", name: "Signage & Seating Charts", icon: "🪧" },
    ],
  },
  {
    group: "Music & Entertainment",
    items: [
      { slug: "dj", name: "DJ", icon: "🎧" },
      { slug: "south-asian-dj", name: "South Asian / Bollywood DJ", icon: "🪩" },
      { slug: "live-band", name: "Live Band", icon: "🎷" },
      { slug: "string-quartet", name: "String Quartet", icon: "🎻" },
      { slug: "dhol-player", name: "Dhol Player", icon: "🥁" },
      { slug: "bagpiper", name: "Bagpiper", icon: "🎶" },
      { slug: "mariachi", name: "Mariachi Band", icon: "🎺" },
      { slug: "lion-dragon-dance", name: "Lion / Dragon Dance Troupe", icon: "🐉" },
      { slug: "mc-anchor", name: "MC / Bilingual Anchor", icon: "🎤" },
      { slug: "sangeet-choreographer", name: "Sangeet Choreographer", icon: "💃" },
      { slug: "fireworks-sparklers", name: "Cold Sparklers / Fireworks", icon: "🎆" },
      { slug: "co2-confetti", name: "CO2 Cannons & Confetti", icon: "🎉" },
    ],
  },
  {
    group: "Beauty & Attire",
    items: [
      { slug: "hmua-bridal", name: "Bridal Hair & Makeup", icon: "💄" },
      { slug: "hmua-south-asian", name: "South Asian HMUA", icon: "✨" },
      { slug: "mehndi-artist", name: "Mehndi / Henna Artist", icon: "🌿" },
      { slug: "bridal-wear", name: "Bridal Wear (Lehenga / Gown)", icon: "👰" },
      { slug: "groom-wear", name: "Groomwear (Sherwani / Tux)", icon: "🤵" },
      { slug: "qipao-hanbok", name: "Qipao / Hanbok / Ao Dai", icon: "👘" },
      { slug: "jewelry-rental", name: "Bridal Jewelry & Rentals", icon: "💍" },
      { slug: "turban-tying", name: "Turban / Pagri Tying", icon: "🧣" },
      { slug: "gele-tying", name: "Gele Tying", icon: "👑" },
    ],
  },
  {
    group: "Logistics & Stationery",
    items: [
      { slug: "stationery-invites", name: "Invitations & Stationery", icon: "💌" },
      { slug: "transportation", name: "Limo / Party Bus / Vintage Car", icon: "🚗" },
      { slug: "baraat-horse", name: "Baraat Horse / Doli", icon: "🐎" },
      { slug: "av-sound", name: "Sound & AV / Translation", icon: "🔊" },
      { slug: "security-valet", name: "Security & Valet", icon: "🛡️" },
      { slug: "wedding-insurance", name: "Wedding Insurance", icon: "📑" },
      { slug: "honeymoon-travel", name: "Honeymoon / Travel Agent", icon: "✈️" },
      { slug: "favors-gifting", name: "Favors & Gifting", icon: "🎁" },
    ],
  },
];

export const allServices = serviceCategories.flatMap((g) =>
  g.items.map((i) => ({ ...i, group: g.group }))
);

export const cities = [
  "Toronto, ON",
  "Mississauga, ON",
  "Brampton, ON",
  "Vancouver, BC",
  "Surrey, BC",
  "Calgary, AB",
  "Edmonton, AB",
  "Montréal, QC",
  "Ottawa, ON",
  "Winnipeg, MB",
  "Halifax, NS",
];

// Demo seed vendors. Photos are emoji-driven — no external images required.
export const seedVendors = [
  {
    id: "v-rajwada",
    name: "Rajwada Banquet & Mandap",
    tagline: "Toronto's most-booked South Asian banquet — 1,200 guest capacity.",
    services: ["banquet-hall", "mandap-decor"],
    cultures: ["south-asian", "fusion-multicultural"],
    city: "Mississauga, ON",
    priceFrom: 18000,
    rating: 4.9,
    reviews: 312,
    badge: "Top Pick",
    emoji: "🛕",
    yearsActive: 14,
    languages: ["English", "Hindi", "Punjabi", "Gujarati"],
    bio: "A flagship Mississauga banquet hall offering halal, vegetarian and Jain menus, in-house mandap decor, baraat staging, and same-day Sangeet conversions.",
  },
  {
    id: "v-niagara-vines",
    name: "Niagara Vines Estate",
    tagline: "Vineyard ceremonies and lantern-lit barrel-room receptions.",
    services: ["vineyard-winery", "estate-mansion", "garden-outdoor"],
    cultures: ["traditional-canadian", "fusion-multicultural", "lgbtq-friendly"],
    city: "Niagara-on-the-Lake, ON",
    priceFrom: 22000,
    rating: 4.8,
    reviews: 198,
    badge: "Editors' Choice",
    emoji: "🍇",
    yearsActive: 9,
    languages: ["English", "French"],
    bio: "Family-run vineyard with chapel, lakeside arch, barrel-room dining and a vintage Citroën for the getaway shot.",
  },
  {
    id: "v-double-happiness",
    name: "Double Happiness Catering",
    tagline: "Cantonese banquet specialists — 10-course tradition done right.",
    services: ["caterer-east-asian"],
    cultures: ["east-asian", "fusion-multicultural"],
    city: "Toronto, ON",
    priceFrom: 95,
    rating: 4.9,
    reviews: 274,
    emoji: "🥢",
    yearsActive: 22,
    languages: ["English", "Cantonese", "Mandarin"],
    bio: "Suckling pig, abalone, lobster e-fu and an in-house roast master. Tea ceremony coordination included.",
  },
  {
    id: "v-amrit-dhol",
    name: "Amrit Dhol Crew",
    tagline: "Two dholis, one dhol-tasha drumline. Loudest baraats in the GTA.",
    services: ["dhol-player", "south-asian-dj"],
    cultures: ["south-asian"],
    city: "Brampton, ON",
    priceFrom: 800,
    rating: 5.0,
    reviews: 156,
    badge: "Crowd Favourite",
    emoji: "🥁",
    yearsActive: 11,
    languages: ["English", "Punjabi"],
    bio: "From a single dhol for the cocktail entrance to a 6-piece dhol-tasha line for the baraat. Costumes included.",
  },
  {
    id: "v-aurora-frames",
    name: "Aurora Frames Photo+Video",
    tagline: "Cinematic same-day-edits and unobtrusive documentary photography.",
    services: ["photographer", "videographer", "drone-operator"],
    cultures: [
      "south-asian",
      "east-asian",
      "traditional-canadian",
      "fusion-multicultural",
      "lgbtq-friendly",
    ],
    city: "Toronto, ON",
    priceFrom: 4500,
    rating: 4.9,
    reviews: 421,
    badge: "Top Pick",
    emoji: "📷",
    yearsActive: 8,
    languages: ["English", "Mandarin", "Hindi"],
    bio: "A 4-shooter team that has covered three-day Hindu weddings, Korean paebaek and lakeside elopements with equal ease.",
  },
  {
    id: "v-sofreh-house",
    name: "Sofreh House",
    tagline: "Persian sofreh aghd design — heirloom mirrors, hand-painted termeh.",
    services: ["mandap-decor", "ceremony-arch", "florist"],
    cultures: ["middle-eastern-persian", "fusion-multicultural"],
    city: "North York, ON",
    priceFrom: 3200,
    rating: 4.9,
    reviews: 88,
    emoji: "🌸",
    yearsActive: 6,
    languages: ["English", "Farsi"],
    bio: "Authentic sofreh aghd builds with seven symbolic items, plus modern fusion arches for the ceremony.",
  },
  {
    id: "v-noor-mehndi",
    name: "Noor Mehndi Studio",
    tagline: "Bridal mehndi with Arabic, Indian and Moroccan styling.",
    services: ["mehndi-artist"],
    cultures: ["south-asian", "middle-eastern-persian", "african-caribbean"],
    city: "Mississauga, ON",
    priceFrom: 350,
    rating: 4.9,
    reviews: 240,
    emoji: "🌿",
    yearsActive: 10,
    languages: ["English", "Urdu", "Arabic"],
    bio: "Bridal mehndi packages, plus on-site team for guest mehndi during the sangeet.",
  },
  {
    id: "v-rosehip-florals",
    name: "Rosehip Florals",
    tagline: "Garden-style florals, hanging installations and chuppah builds.",
    services: ["florist", "chuppah-decor", "ceremony-arch"],
    cultures: [
      "traditional-canadian",
      "jewish",
      "fusion-multicultural",
      "lgbtq-friendly",
    ],
    city: "Toronto, ON",
    priceFrom: 2800,
    rating: 4.8,
    reviews: 167,
    emoji: "💐",
    yearsActive: 7,
    languages: ["English"],
    bio: "Locally sourced blooms, suspended floral clouds, and full chuppah construction with reusable hardware.",
  },
  {
    id: "v-hanbok-house",
    name: "Hanbok House",
    tagline: "Hanbok rentals, paebaek setup and traditional Korean styling.",
    services: ["qipao-hanbok", "mandap-decor", "bridal-wear", "groom-wear"],
    cultures: ["east-asian", "fusion-multicultural"],
    city: "North York, ON",
    priceFrom: 600,
    rating: 4.9,
    reviews: 73,
    emoji: "👘",
    yearsActive: 5,
    languages: ["English", "Korean"],
    bio: "Modern and traditional hanbok rentals, paebaek table setup, and styling assistants on site.",
  },
  {
    id: "v-glasshouse-tents",
    name: "Glasshouse Tent Co.",
    tagline: "Clear-span sailcloth tents, transparent roofs and stargazer panels.",
    services: ["drape-tent", "lighting-design", "furniture-rental"],
    cultures: ["traditional-canadian", "fusion-multicultural", "jewish"],
    city: "Burlington, ON",
    priceFrom: 9500,
    rating: 4.7,
    reviews: 54,
    emoji: "⛺",
    yearsActive: 12,
    languages: ["English"],
    bio: "Engineered tent installs from 100 to 600 guests with full power, climate, lounge furniture and dance floor.",
  },
  {
    id: "v-baraat-horse",
    name: "Royal Baraat Stables",
    tagline: "White stallion baraats, decorated doli and vintage car packages.",
    services: ["baraat-horse", "transportation"],
    cultures: ["south-asian"],
    city: "Brampton, ON",
    priceFrom: 1200,
    rating: 4.8,
    reviews: 95,
    emoji: "🐎",
    yearsActive: 16,
    languages: ["English", "Punjabi", "Hindi"],
    bio: "Insured, licensed handlers; horse, carriage, doli and a Rolls-Royce Phantom getaway car.",
  },
  {
    id: "v-aria-cakes",
    name: "Aria Cakes & Mithai",
    tagline: "Six-tier cakes by day, mithai towers by night.",
    services: ["cake-designer", "mithai-sweets", "dessert-grazing"],
    cultures: ["south-asian", "traditional-canadian", "fusion-multicultural"],
    city: "Vaughan, ON",
    priceFrom: 850,
    rating: 4.9,
    reviews: 312,
    emoji: "🎂",
    yearsActive: 9,
    languages: ["English", "Punjabi"],
    bio: "Hand-painted sugar florals, eggless and halal options, and a 100-piece mithai tower for the sweet table.",
  },
  {
    id: "v-fiesta-mariachi",
    name: "Fiesta Mariachi GTA",
    tagline: "Eight-piece mariachi serenade for the surprise of a lifetime.",
    services: ["mariachi", "live-band"],
    cultures: ["latin-american", "fusion-multicultural"],
    city: "Toronto, ON",
    priceFrom: 1400,
    rating: 5.0,
    reviews: 41,
    emoji: "🎺",
    yearsActive: 7,
    languages: ["English", "Spanish"],
    bio: "Authentic mariachi from Jalisco-trained musicians — ceremony serenade, hora loca finale, or both.",
  },
  {
    id: "v-clan-pipes",
    name: "Clan & Pipes",
    tagline: "Bagpipe processionals and Highland piping for ceremony entrances.",
    services: ["bagpiper"],
    cultures: ["traditional-canadian"],
    city: "Ottawa, ON",
    priceFrom: 450,
    rating: 4.9,
    reviews: 64,
    emoji: "🎶",
    yearsActive: 18,
    languages: ["English"],
    bio: "Solo piper or pipe-and-drums band, in full Highland dress, available across Ontario and Quebec.",
  },
  {
    id: "v-aso-ebi",
    name: "Aso Ebi Atelier",
    tagline: "Custom Nigerian wedding attire, gele tying, and family co-ordination.",
    services: ["bridal-wear", "groom-wear", "gele-tying"],
    cultures: ["african-caribbean", "fusion-multicultural"],
    city: "Toronto, ON",
    priceFrom: 1800,
    rating: 4.9,
    reviews: 58,
    emoji: "👑",
    yearsActive: 6,
    languages: ["English", "Yoruba", "Igbo"],
    bio: "Aso ebi packages for the bridal party, hand-tied gele on the morning, and same-day groom agbada fittings.",
  },
  {
    id: "v-koshergrand",
    name: "Kosher Grand Catering",
    tagline: "Glatt-kosher reception menus under rabbinical supervision.",
    services: ["caterer-kosher"],
    cultures: ["jewish"],
    city: "Thornhill, ON",
    priceFrom: 145,
    rating: 4.8,
    reviews: 122,
    emoji: "🕎",
    yearsActive: 20,
    languages: ["English", "Hebrew"],
    bio: "Glatt-kosher dairy and meat menus, mezze stations, full chuppah dinner service and post-bedeken hors d'oeuvres.",
  },
  {
    id: "v-pacific-bartend",
    name: "Pacific Mobile Bartending",
    tagline: "Smartserve-certified bartenders, mocktail bars and chai stations.",
    services: ["bartending", "barista-tea"],
    cultures: [
      "traditional-canadian",
      "south-asian",
      "east-asian",
      "fusion-multicultural",
      "lgbtq-friendly",
    ],
    city: "Vancouver, BC",
    priceFrom: 1500,
    rating: 4.9,
    reviews: 207,
    emoji: "🍸",
    yearsActive: 8,
    languages: ["English"],
    bio: "Full bar setup with glassware, ice service, dry-bar / mocktail menus and chai or boba bar add-ons.",
  },
  {
    id: "v-elder-circle",
    name: "Elder Circle Ceremonies",
    tagline: "Indigenous-led smudging, blanket and sacred-fire ceremonies.",
    services: ["indigenous-elder", "interfaith-officiant"],
    cultures: ["indigenous-canadian", "fusion-multicultural"],
    city: "Ottawa, ON",
    priceFrom: 600,
    rating: 5.0,
    reviews: 22,
    emoji: "🪶",
    yearsActive: 15,
    languages: ["English", "Anishinaabemowin"],
    bio: "Elder-led ceremonies coordinated with respect to family nation and protocol; available across Ontario.",
  },
];

export function getVendorById(id) {
  return seedVendors.find((v) => v.id === id);
}

export function getCultureBySlug(slug) {
  return cultures.find((c) => c.slug === slug);
}

export function getServiceBySlug(slug) {
  return allServices.find((s) => s.slug === slug);
}
